config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'contact', to:'static_pages#contact'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :reservations
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  


  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_secure_password



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user , :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservations_path
    else
      render 'new'
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      redirect_to reservations_path
    else
      render 'new'
    end
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if @reservation.destroy
      redirect_to reservations_path
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:motiv, :choose)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,:email,:password,:city,:address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prov5</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_reservation_form.html.erb
<%= form_for @reservation do |f| %>
  <ul>
    <li><%= f.label :motiv %></li>
    <li><%= f.text_field :motiv %></li><br/>
    <li><%= f.label :choose %></li>
    <li><%= f.datetime_field :choose %></li><br/>

    <li><%= f.submit %></li><br/>

  </ul>
  <% end %>

app/views/reservations/edit.html.erb
<%= render 'reservation_form'%>

app/views/reservations/index.html.erb
<h1>List of reservations </h1>
<%= link_to 'Create reservations', new_reservation_path %>
<br/>
<br/>
<% @reservations.each do |reservation| %>
  <ul>

    <li><%= reservation.motiv %></li>
    <li><%= reservation.choose%></li>
    <li><%= link_to 'View', reservation_path(reservation) %></li>
    <li><%= link_to 'Edit', edit_reservation_path(reservation) %>
    <li><%= link_to 'Delete', reservation_path(reservation), method: :delete, data: {confirm: "Are you sure" }%>
  </ul>
<% end %>

app/views/reservations/new.html.erb
<%= render 'reservation_form' %>

app/views/reservations/show.html.erb
<h1>Show your termin </h1>
<%= link_to 'Back to list', reservations_path %>
<br>
<%= @reservation.motiv %>
<%= @reservation.choose %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/_user_form.html.erb
<%= form_for @user do |t| %>
  <ul>
    <li><%= t.label :username %></li>
    <li><%= t.text_field :username %></li><br/>
    <li><%= t.label :email %></li>
    <li><%= t.email_field :email %></li><br/>
    <li><%= t.label :password %></li>
    <li><%= t.password_field :password %></li><br/>
    <li><%= t.label :city %></li>
    <li><%= t.text_field :city %></li><br/>
    <li><%= t.label :address %></li>
    <li><%= t.text_field :address %></li><br/>

    <li><%= t.submit %></li><br/>

  </ul>


<% end %>

app/views/users/edit.html.erb
<%= render 'user_form' %>

app/views/users/index.html.erb
<h1>All Users</h1>
<%= link_to 'Create new user', signup_path %>
<% @users.each do |user| %>
  <ul>
  <li><%= user.username %></li>
  <li><%= user.email %></li>
  <li><%= user.city %></li>
  <li><%= user.address %></li>
  <li><%= link_to 'edit', edit_user_path(user) %></li>
  <li><%= link_to 'view', user_path(user) %></li>
  <li><%= link_to 'delete', user_path(user), method: :delete, data: { confirm: "Are you sure" } %></li>
  </ul>
<%end%>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= render 'user_form' %>

app/views/users/show.html.erb
<h1>Welcome to your blog <%= @user.username %></h1>
<%= link_to 'Back to list ', users_path %>
<h3>History</h3>
<h5><%= @user.email %></h5>
<h5><%= @user.address %></h5>
<h5><%= @user.city %></h5>
<%= link_to 'Edit your privatcy', edit_user_path %>